### ISSUE TITLE
Smart Contract

### ISSUE THREAD

**Issue by djLeeee** [codestates/beb-03-DDYY#8]
## Bare Minimum

- [x] truffle 환경설정 확인하기
- [x] ERC721 NFT  발행 컨트랙트 작성하기
- [x] ERC721 NFT 전송 컨트랙트 작성하기

## Advanced
- [ ] ERC721 NFT  판매 컨트랙트 작성하기

**Comment by journiyoon** [comment]
아직 감이 안잡혀서 유어클래스 제목만 적었는데 22시 전까지 내용 파악해서 보충하겠습니다.

**Comment by journiyoon** [comment]
혹시 필요한 의견주시면 반영하겠습니다!
